version: '2'
services:
  ros-master:
    image: frankjoshua/rpi-ros-master
    ports:
      - "11311:11311"
    env_file:
      - ros.env
    network_mode: "host"
    restart: always

  ros-qtr:
    image: frankjoshua/ros-rpi-qtr-8rc
    cap_add: 
      - SYS_RAWIO
    devices: 
      - "/dev/mem:/dev/mem"
    privileged: true
    env_file:
      - ros.env
    network_mode: "host"
    restart: always

  ros-oled-display:
    image: frankjoshua/ros-rpi-oled-display
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
    privileged: true
    env_file:
      - ros.env
    network_mode: "host"
    restart: always

  ros-l298:
    image: frankjoshua/gobbit-l298n-ros-node
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
    volumes:
      - /home/pirate/gobbit:/home/pi/gobbit
    command: /home/pi/gobbit/L295_ros_node_docker/run.sh
    privileged: true
    env_file:
      - ros.env
    network_mode: "host"
    restart: always

  web-server:
    image: schoeffm/rpi-nginx-php5
    network_mode: "host"
    restart: always
    volumes:
      - /home/pirate/gobbit/blockly:/usr/share/nginx/www

  ros-line-follower:
    image: frankjoshua/ros-rpi-line-follower
    env_file:
      - ros.env
    network_mode: "host"
    restart: always
    
  ros-line-follower:
    image: frankjoshua/user_code_node
    env_file:
      - ros.env
    network_mode: "host"
    restart: always
    volumes:
      - /home/pirate/gobbit/blockly/combined_code.py:/usr/share/nginx/www

