version: '3'
services:
    
############################ LINE FOLLOWER ############################

  # ros-rpi-cam-v1:
  #   image: frankjoshua/ros-rpi-cam-v1
  #   build: ./docker_ros_nodes/ros-rpi-cam-v1
  #   devices:
  #     - "/dev/video0:/dev/video0"
  #   privileged: true
  #   volumes:
  #     - $HOME/gobbit/docker_ros_nodes/ros-rpi-cam-v1/ros.launch:/ros.launch
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped

  # ros-motor-hat:
  #   image: frankjoshua/ros-adafruit-motor-hat
  #   build: ./docker_ros_nodes/ros-adafruit-motor-hat
  #   cap_add:
  #     - SYS_RAWIO
  #   devices:
  #     - "/dev/i2c-1:/dev/i2c-1"
  #     - "/lib/modules:/lib/modules"
  #     - "/dev/mem:/dev/mem"
  #   volumes:
  #     - /home/pirate/gobbit:/home/pi/gobbit
  #     - $HOME/gobbit/docker_ros_nodes/ros-adafruit-motor-hat/node.py:/node.py
  #   privileged: true
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped
    
############################ EFIM ############################

  # ros-arduino-serial:
  #   image: "frankjoshua/ros-arduino-serial:${ARCH:-latest}"
  #   build: ./docker_ros_nodes/ros_arduino_serial
  #   env_file:
  #     - ros.env
  #   privileged: true
  #   network_mode: "host"
  #   volumes:
  #     - /dev/ttyACM2:/dev/arduino_motor
  #     - /home/nvidia/ros:/root/.ros
  #   restart: unless-stopped

  # ros-hokuyo-laser:
  #   image: "frankjoshua/ros-hokuyo-laser:${ARCH:-latest}"
  #   build: ./docker_ros_nodes/ros-hokuyo-laser
  #   devices:
  #     - "/dev/ttyACM0:/dev/hokuyo"
  #   volumes:
  #     - "$HOME/gobbit/docker_ros_nodes/ros-hokuyo-laser/ros.launch:/ros.launch"
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped
    
  # ros-kinect:
  #   image: "frankjoshua/ros-kinect:${ARCH:-latest}"
  #   build: ./docker_ros_nodes/ros-kinect
  #   privileged: true
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped

############################ OTHER ############################

  ros-usb-cam:
    image: frankjoshua/ros-usb-cam
    build: ./docker_ros_nodes/ros-usb-cam
    devices:
      - "/dev/video1:/dev/video0"
    env_file:
      - ros.env
    network_mode: "host"
    #command: rosrun uvc_camera uvc_camera_node _width:=160 _height:=120 _fps:=30
    command: rosrun usb_cam usb_cam_node _width:=640 _height:=480 _fps:=30 _camera_frame_id:=camera_ceiling _camera_info_url:=file:///calibration.yaml _pixel_format:=yuyv
  
  # ros-xv-11-laser:
  #   image: "frankjoshua/docker_ros_xv_11:${ARCH:-latest}"
  #   build: ./docker_ros_nodes/docker_ros_xv_11
  #   devices:
  #     - "/dev/ttyACM0:/dev/laser_port"
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped

  # ros-ultimate-hat-node:
  #   image: frankjoshua/ros-rpi-ultimate-hat-node
  #   cap_add:
  #     - SYS_RAWIO
  #   devices:
  #     - "/dev/mem:/dev/mem"
  #     - "/lib/modules:/lib/modules"
  #     - "/dev/i2c-1:/dev/i2c-1"
  #   volumes:
  #     - "$HOME/gobbit/ultimate_hat_node/node.py:/node.py"
  #   privileged: true
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped

  # ros-linedog:
  #   image: frankjoshua/ros-rpi-linedog-node
  #   cap_add:
  #     - SYS_RAWIO
  #   devices:
  #     - "/dev/mem:/dev/mem"
  #     - "/lib/modules:/lib/modules"
  #     - "/dev/i2c-1:/dev/i2c-1"
  #   volumes:
  #     - "/home/pirate/gobbit/linedog_node/node.py:/node.py"
  #   privileged: true
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped

  # ros-oled-display:
  #   image: frankjoshua/ros-rpi-oled-display
  #   cap_add:
  #     - SYS_RAWIO
  #   devices:
  #     - "/dev/mem:/dev/mem"
  #     - "/lib/modules:/lib/modules"
  #     - "/dev/i2c-1:/dev/i2c-1"
  #   privileged: true
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped
