---
version: '3'
services:

  ros-arduino-serial:
    image: "frankjoshua/ros-arduino-serial:${ARCH:-latest}"
    build: ./docker_ros_nodes/ros_arduino_serial
    env_file:
      - ros.env
    network_mode: "host"
    command: rosrun rosserial_server socket_node

  ros-master:
    image: "frankjoshua/ros-master:${ARCH:-latest}"
    build: ./docker_ros_nodes/ros-master
    volumes:
      - $HOME/ros:/root/.ros
    env_file:
      - ros.env
    network_mode: "host"

  ros-thermal-dnn:
    image: "frankjoshua/ros-thermal-dnn:${ARCH:-latest}"
    build: ./docker_ros_nodes/ros-thermal-dnn
    volumes:
      - $HOME/gobbit/docker_ros_nodes/ros-thermal-dnn/node.py:/node.py
      - $HOME/notebooks:/notebooks
    env_file:
      - ros.env
    network_mode: "host"
