version: '2'
services:
  ros-master:
    image: frankjoshua/rpi-ros-master
    ports:
      - "11311:11311"
    env_file:
      - ros.env
    network_mode: "host"
    restart: unless-stopped

  ros-qtr:
    image: frankjoshua/ros-rpi-qtr-8rc
    cap_add: 
      - SYS_RAWIO
    devices: 
      - "/dev/mem:/dev/mem"
    privileged: true
    env_file:
      - ros.env
    network_mode: "host"
    restart: unless-stopped

  ros-oled-display:
    image: frankjoshua/ros-rpi-oled-display
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/lib/modules:/lib/modules"
      - "/dev/i2c-1:/dev/i2c-1"
    privileged: true
    env_file:
      - ros.env
    network_mode: "host"
    restart: unless-stopped

  ros-motor-hat:
    image: frankjoshua/ros-rpi-adafruit-motor-hat
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/lib/modules:/lib/modules"
      - "/dev/mem:/dev/mem"
    volumes:
      - /home/pirate/gobbit:/home/pi/gobbit
    privileged: true
    env_file:
      - ros.env
    network_mode: "host"
    restart: unless-stopped

  web-server:
    image: schoeffm/rpi-nginx-php5
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /home/pirate/gobbit/blockly:/usr/share/nginx/www

  ros-line-follower:
    image: frankjoshua/ros-rpi-line-follower
    env_file:
      - ros.env
    network_mode: "host"
    restart: unless-stopped

