version: '2.1'
services:
  #  ros-arduino-serial:
  #    image: "frankjoshua/ros-arduino-serial:${ARCH:-latest}"
  #    build: ./docker_ros_nodes/ros_arduino_serial
  #    env_file:
  #      - ros.env
  #    privileged: true
  #    network_mode: "host"
  #    volumes:
  #      - /dev/ttyACM0:/dev/arduino_motor
  #    restart: unless-stopped

#  ros-xv-11-laser:
#    image: "frankjoshua/docker_ros_xv_11:${ARCH:-latest}"
#    build: ./docker_ros_nodes/docker_ros_xv_11
#    devices:
#      - "/dev/ttyACM0:/dev/laser_port"
#    env_file:
#      - ros.env
#    network_mode: "host"
#    restart: unless-stopped

  # ros-hokuyo-laser:
  #   image: "frankjoshua/ros-hokuyo-laser:${ARCH:-latest}"
  #   build: ./docker_ros_nodes/ros-hokuyo-laser
  #   devices:
  #     - "/dev/ttyACM0:/dev/ttyACM0"
  #   volumes:
  #     - "$HOME/gobbit/docker_ros_nodes/ros-hokuyo-laser/ros.launch:/ros.launch"
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped
  
  ros-usb-cam:
    image: frankjoshua/ros-usb-cam
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
    env_file:
      - ros.env
    network_mode: "host"
    restart: unless-stopped

  ros-motor-hat:
    image: frankjoshua/ros-rpi-adafruit-motor-hat
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/lib/modules:/lib/modules"
      - "/dev/mem:/dev/mem"
    volumes:
      - /home/pirate/gobbit:/home/pi/gobbit
    privileged: true
    env_file:
      - ros.env
    network_mode: "host"
    restart: unless-stopped

  # ros-ultimate-hat-node:
  #   image: frankjoshua/ros-rpi-ultimate-hat-node
  #   cap_add:
  #     - SYS_RAWIO
  #   devices:
  #     - "/dev/mem:/dev/mem"
  #     - "/lib/modules:/lib/modules"
  #     - "/dev/i2c-1:/dev/i2c-1"
  #   volumes:
  #     - "$HOME/gobbit/ultimate_hat_node/node.py:/node.py"
  #   privileged: true
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped

  # ros-linedog:
  #   image: frankjoshua/ros-rpi-linedog-node
  #   cap_add:
  #     - SYS_RAWIO
  #   devices:
  #     - "/dev/mem:/dev/mem"
  #     - "/lib/modules:/lib/modules"
  #     - "/dev/i2c-1:/dev/i2c-1"
  #   volumes:
  #     - "/home/pirate/gobbit/linedog_node/node.py:/node.py"
  #   privileged: true
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped

  # ros-oled-display:
  #   image: frankjoshua/ros-rpi-oled-display
  #   cap_add:
  #     - SYS_RAWIO
  #   devices:
  #     - "/dev/mem:/dev/mem"
  #     - "/lib/modules:/lib/modules"
  #     - "/dev/i2c-1:/dev/i2c-1"
  #   privileged: true
  #   env_file:
  #     - ros.env
  #   network_mode: "host"
  #   restart: unless-stopped
