---
version: '3'
services:

  ros-irobot-create-2:
    image: "frankjoshua/ros-irobot-create-2:${ARCH:-latest}"
    build: ./docker_ros_nodes/ros-irobot-create-2
    devices:
      - /dev/create2:/dev/ttyUSB0
    env_file:
      - ros.env
    volumes:
      - $HOME/gobbit/docker_ros_nodes/ros-irobot-create-2/config.yaml:/config.yaml
      - $HOME/gobbit/docker_ros_nodes/ros-irobot-create-2/ros.launch:/ros.launch
    network_mode: "host"

  # ros-hector-mapping:
  #   image: "frankjoshua/ros-hector-mapping:${ARCH:-latest}"
  #   build: ./docker_ros_nodes/ros-hector-mapping
  #   volumes:
  #     - $HOME/gobbit/docker_ros_nodes/ros-hector-mapping/ros.launch:/ros.launch
  #   env_file:
  #     - ros.env
  #   network_mode: "host"

  # ros-move-base:
  #   image: "frankjoshua/ros-move-base:${ARCH:-latest}"
  #   build: ./docker_ros_nodes/ros-move-base
  #   env_file:
  #     - ros.env
  #   volumes:
  #     - $HOME/gobbit/docker_ros_nodes/ros-move-base/ros.launch:/ros.launch
  #     - $HOME/gobbit/docker_ros_nodes/ros-move-base/base_local_planner_params.yaml:/base_local_planner_params.yaml
  #     - $HOME/gobbit/docker_ros_nodes/ros-move-base/costmap_common_params.yaml:/costmap_common_params.yaml
  #     - $HOME/gobbit/docker_ros_nodes/ros-move-base/global_costmap_params.yaml:/global_costmap_params.yaml
  #     - $HOME/gobbit/docker_ros_nodes/ros-move-base/local_costmap_params.yaml:/local_costmap_params.yaml
  #   network_mode: "host"

  # ros-gmapping:
  #   image: frankjoshua/ros-gmapping
  #   volumes:
  #     - $HOME/gobbit/docker_ros_nodes/gmapping/ros.launch:/ros.launch
  #   env_file:
  #     - ros.env
  #   network_mode: "host"

  ros-ydlidar-x4:
    image: "frankjoshua/ros-ydlidar-x4:${ARCH:-latest}"
    build: ./docker_ros_nodes/ros-ydlidar-x4
    devices:
      - /dev/ydlidar:/dev/ydlidar
    env_file:
      - ros.env
    network_mode: "host"
